export const DELETE_ITEM_FROM_DATA_LIST='DELETE_ITEM_FROM_DATA_LIST';
export const ADD_ITEM_To_DATA_LIST='ADD_ITEM_To_DATA_LIST';
export const Chek_Is_Go_Next='Chek_Is_Go_Next';
export const UPDITE_ITEM_FROM_DATA_LIST='DELETE_ITEM_FROM_DATA_LIST';
